CREATE TABLE [dbo].[BALL_ENGINE_LIST] (
    [ID]                       INT           IDENTITY (1, 1) NOT NULL,
    [ENGINE_TYPE]              CHAR (4)      NOT NULL,
    [ENGINE_NO]                CHAR (6)      NOT NULL,
    [ENGINE_ASM_NO]            CHAR (10)     NOT NULL,
    [BOOK]                     CHAR (2)      NOT NULL,
    [YEAR]                     VARCHAR (4)   NOT NULL,
    [MODEL_CODE]               CHAR (8)      NOT NULL,
    [LOT_NO]                   VARCHAR (4)   NOT NULL,
    [UNIT_NO]                  VARCHAR (2)   NOT NULL,
    [AT_MT]                    CHAR (2)      NOT NULL,
    [EMISSION]                 CHAR (2)      NOT NULL,
    [INJ_MODEL_CODE]           CHAR (2)      NOT NULL,
    [SPARE_001]                CHAR (2)      NOT NULL,
    [SB_DATA_SB_PARTS_NO]      CHAR (10)     NOT NULL,
    [SB_DATA_SB_SERIAL_NO]     CHAR (6)      NOT NULL,
    [SB_DATA_GASKET_GRADE]     CHAR (2)      NOT NULL,
    [LINE_ON_TIME]             DATETIME      NOT NULL,
    [LINE_OFF_TIME]            DATETIME      NOT NULL,
    [RPCOCF_SBLO_BCT]          CHAR (2)      NOT NULL,
    [RPCOCF_SBLO_CRT]          CHAR (2)      NOT NULL,
    [RPCOCF_SBLO_CTM]          CHAR (2)      NOT NULL,
    [RPCOCF_SBLO_SPARE01]      CHAR (2)      NOT NULL,
    [RPCOCF_SBLO_SPARE02]      CHAR (2)      NOT NULL,
    [RPCOCF_SBLO_SPARE03]      CHAR (2)      NOT NULL,
    [RPCOCF_MALO_CCT]          CHAR (2)      NOT NULL,
    [RPCOCF_MALO_DPT]          CHAR (2)      NOT NULL,
    [RPCOCF_MALO_FWT]          CHAR (2)      NOT NULL,
    [RPCOCF_MALO_SPARE01]      CHAR (2)      NOT NULL,
    [RPCOCF_MALO_SPARE02]      CHAR (2)      NOT NULL,
    [RPCOCF_MALO_SPARE03]      CHAR (2)      NOT NULL,
    [RPCOCF_MBLO_HDT]          CHAR (2)      NOT NULL,
    [RPCOCF_MBLO_CCT]          CHAR (2)      NOT NULL,
    [RPCOCF_MBLO_HCT]          CHAR (2)      NOT NULL,
    [RPCOCF_MBLO_PPT]          CHAR (2)      NOT NULL,
    [RPCOCF_MBLO_SPARE01]      CHAR (2)      NOT NULL,
    [RPCOCF_MBLO_SPARE02]      CHAR (2)      NOT NULL,
    [RPCOCF_MBLO_SPARE03]      CHAR (2)      NOT NULL,
    [RPCOCF_MBLO_SPARE04]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION01]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION02]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION03]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION04]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION05]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION06]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION_TIME01] DATETIME      NOT NULL,
    [INSPSJ_INSPECTION11]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION12]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION13]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION14]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION15]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION16]      CHAR (2)      NOT NULL,
    [INSPSJ_INSPECTION_TIME02] DATETIME      NOT NULL,
    [CREATED_BY]               VARCHAR (255) NOT NULL,
    [UPDATED_BY]               VARCHAR (255) NULL,
    [CREATED_WHEN]             DATETIME      CONSTRAINT [DF_BALL_ENGINE_LIST_CREATED_WHEN] DEFAULT (getdate()) NOT NULL,
    [UPDATED_WHEN]             DATETIME      NULL,
    CONSTRAINT [PK_BALL_ENGINE_LIST] PRIMARY KEY CLUSTERED ([ID] ASC)
);

